UPDATE users SET role = 'ARTICLE' WHERE role = 'ARTICLE_MANAGER';
UPDATE users SET role = 'PRODUCT' WHERE role = 'PRODUCT_MANAGER';
UPDATE users SET role = 'CATEGORY' WHERE role = 'CATEGORY_MANAGER';
