CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (name)
SELECT DISTINCT TRIM(department)
FROM managers
WHERE department IS NOT NULL AND TRIM(department) <> ''
ON CONFLICT (name) DO NOTHING;

ALTER TABLE managers ADD COLUMN department_id BIGINT;
ALTER TABLE managers ADD COLUMN address_detail VARCHAR(160);
ALTER TABLE managers ADD COLUMN ward VARCHAR(80);
ALTER TABLE managers ADD COLUMN district VARCHAR(80);
ALTER TABLE managers ADD COLUMN province VARCHAR(80);

UPDATE managers manager
SET department_id = department.id
FROM departments department
WHERE manager.department IS NOT NULL
  AND department.name = TRIM(manager.department);

ALTER TABLE managers DROP COLUMN department;
ALTER TABLE managers
    ADD CONSTRAINT fk_managers_department
    FOREIGN KEY (department_id) REFERENCES departments(id);
